version: '3.5'

services:
  frontend:
    build: ./frontend
    ports:
      - 5000:5000
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./logs.txt:/app/logs.txt
    environment:
      - REDIS=cache
      - DB_USERNAME=postgres
      - DB_PASSWORD=somepass
      - DB_NAME=postgres
      - DB_HOST=db
    depends_on:
      - db
      - cache
  cache:
    image: redis
    restart: unless-stopped
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: somepass
  load-balancer:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend