version: '3.5'

services:
  frontend:
    build: ./frontend
    ports:
      - 5000:5000
  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./logs.txt:/app/logs.txt
    environment:
      - REDIS=cache
  cache:
    image: redis
    restart: unless-stopped
